<section>
<div class="container">
<div class="privacy_policy">
<h2>Terms Of Use For Information Dissemination</h2>

<div class="accept_prt">
<span class="misc">Your Acceptance of this Agreement</span>
<p>This is an agreement between you ("you" or "your") and Weblistrwith its office at Harrington Mansion 3rd Floor 28/4, Ho Chi Minh Sarani, Kolkata 700 071 ("Weblistr" "we," or "our") that governs your use of the search services offered by Weblistr through its website www.Weblistr.com ("Website") or any other medium using which Weblistr may provide the search services (collectively "Platforms" ). When you access or use any of the Platforms you agree to be bound by these Terms and Conditions ("Terms").</p>
<span class="misc">Changes</span>
<p>We may periodically change the Terms and the Site without notice, and you are responsible for checking these Terms periodically for revisions. All amended Terms become effective upon our posting to the Site, and any use of the site after such revisions have been posted signifies your consent to the changes.</p>
<span class="misc">How you may use our materials</span>
<p>We use a diverse range of information, text, photographs, designs, graphics, images, sound and video recordings, animation, content, advertisement and other materials and effects (collectively "Materials") for the search services on the Platforms. We provide the Material through the Platforms<strong>For your personal and non-commercial use only.</strong></p>
<p>While every attempt has been made to ascertain the authenticity of the Platforms content, Weblistr is not liable for any kind of damages, losses or action arising directly or indirectly, due to access and/or use of the content in the Platforms including but not limited to decisions based on the content in the Platforms which results in any loss of data, revenue, profits, property, infection by viruses etc.</p>
<p>Accordingly, you may view, use, copy, and distribute the Materials found on the Platforms for internal, non-commercial, informational purposes only. You are prohibited from data mining, scraping, crawling, or using any process or processes that send automated queries to Weblistr. You may not use the Platforms or any of them to compile a collection of listings, including a competing listing product or service. You may not use the Platforms or any Materials for any unsolicited commercial e-mail. Except as authorized in this paragraph, you are not being granted a license under any copyright, trademark, patent or other intellectual property right in the Materials or the products, services, processes or technology described therein. All such rights are retained by Weblistr, its subsidiaries, parent companies, and/or any third party owner of such rights.</p>
<span class="misc">How you may use our marks</span>
<p>The Weblistr company names and logos and all related products and service names, design marks and slogans are trademarks and service marks owned by and used under license from Weblistr or it's wholly owned subsidiaries. All other trademarks and service marks herein are the property of their respective owners. All copies that you make of the Materials on any of the Platforms must bear any copyright, trademark or other proprietary notice located on the respective Platforms that pertains to the material being copied. You are not authorized to use any Weblistr name or mark in any advertising, publicity or in any other commercial manner without the prior written consent of Weblistr. Requests for authorization should be made to <a href="#">support@Weblistr.com</a></p>


<span class="misc">How we may use information you provide to us</span>
<p>Do not send us any confidential or proprietary information. Except for any personally identifiable information that we agree to keep confidential as provided in our Privacy Policy, any material, including, but not limited to any feedback, data, answers, questions, comments, suggestions, ideas or the like, which you send to us will be treated as being non-confidential and nonproprietary. We assume no obligation to protect confidential or proprietary information (other than personally identifiable information) from disclosure and will be free to reproduce, use, and distribute the information to others without restriction. We will also be free to use any ideas, concepts, know-how or techniques contained in information that you send us for any purpose whatsoever including but not limited to developing, manufacturing and marketing products and services incorporating such information.
</p>


<span class="misc">Reviews, Ratings & Comments by user</span>
<p>Since, Weblistr provides information directory services through various mediums, your ("Users") use any of the mediums to post Reviews, Ratings and Comments about the Weblistr services and also about the Advertiser's listed at Weblistr is subject to additional terms and conditions as mentioned herein.</p>
<p>You are solely responsible for the content of any transmissions you make to the Site or any transmissions you make to any mediums offered by Weblistr and any materials you add to the Site or add to any mediums offered by Weblistr, including but not limited to transmissions like your Reviews, Ratings & Comments posted by you(the "Communications"). Weblistr does not endorse or accept any of your Communication as representative of their (Weblistr) views. By transmitting any public Communication to the Site, you grant Weblistr an irrevocable, non-exclusive, worldwide, perpetual, unrestricted, royalty-free license (with the right to sublicense) to use, reproduce, distribute, publicly display, publicly perform, adapt, modify, edit, create derivative works from, incorporate into one or more compilations and reproduce and distribute such compilations, and otherwise exploit such Communications, in all Platforms now known or later developed.</p>
<p>You confirm and warrant that you have the right to grant these rights to Weblistr. You hereby waive and grant to Weblistr all rights including intellectual property rights and also "moral rights" in your Communications, posted at Weblistr through any of mediums of Weblistr. Weblistr is free to use all your Communications as per its requirements from time to time. You represent and warrant that you own or otherwise control all of the rights to the content that you post as Review, Rating or Comments; that the content is accurate; that use of the content you supply does not violate these Terms and will not cause injury to any person or entity. For removal of doubts it is clarified that, the reference to Communications would also mean to include the reviews, ratings and comments posted by your Friend's tagged by you. Also Weblistr reserves the right to mask or unmask your identity in respect of your Reviews, Ratings & Comments posted by you.</p>

<p>Weblistr has the right, but not the obligation to monitor and edit or remove any content posted by you as Review, Rating or Comments. Weblistr cannot review all Communications made on and through any of the mediums of Weblistr. However, Weblistr reserves the right, but has no obligation, to monitor and edit, modify or delete any Communications (or portions thereof) which Weblistr in its sole discretion deems inappropriate, offensive or contrary to any Weblistr policy, or that violate this terms:</p>

<p>Weblistr reserves the right not to upload or distribute to, or otherwise publish through the Site or Forums any Communication which</p>
<ul>
<li><p>is obscene, indecent, pornographic, profane, sexually explicit, threatening, or abusive;</p></li>
<li><p>constitutes or contains false or misleading indications of origin or statements of fact;</p></li>
<li><p>slanders, libels, defames, disparages, or otherwise violates the legal rights of any third party;</p></li>
<li><p>causes injury of any kind to any person or entity;</p></li>
<li><p>infringes or violates the intellectual property rights (including copyright, patent and trademark rights), contract rights, trade secrets, privacy or publicity rights or any other rights of any third party;</p></li>
<li><p>violates any applicable laws, rules, or regulations;</p></li>
<li><p>contains software viruses or any other malicious code designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</p></li>
<li><p>Impersonates another person or entity, or that collects or uses any information about Site visitors.</p></li>
</ul>
<p>It is also clarified that, if there are any issues or claims due to your posts by way of Reviews, Ratings and Comments, then Weblistr reserves right to take appropriate legal action against you. Further, you shall indemnify and protect Weblistr against such claims or damages or any issues, due to your posting of such Reviews, Ratings and Comments Weblistr takes no responsibility and assumes no liability for any content posted by you or any third party on Weblistr site or on any mediums of Weblistr.</p>
<p>You further acknowledge that conduct prohibited in connection with your use of the Forums includes, but is not limited to, breaching or attempting to breach the security of the Site or any of the mediums of Weblistr.</p>

<span class="misc">Privacy Policy</span>
<p>Weblistr is committed to protecting the privacy and confidentiality of any personal information that it may request and receive from its clients, business partners and other users of the Website. To read our privacy policy statement regarding such personal information please refer <a href="Privacyterms">Privacy Policy</a></p>
<span class="misc">Content Disclaimer</span>
<p>Weblistr communicates information provided and created by advertisers, content partners, software developers, publishers, marketing agents, employees, users, resellers and other third parties. While every attempt has been made to ascertain the authenticity of the content on the Platforms,Weblistr has no control over content, the accuracy of such content, integrity or quality of such content and the information on our pages, and material on the Platforms may include technical inaccuracies or typographical errors, and we make no guarantees, nor can we be responsible for any such information, including its authenticity, currency, content, quality, copyright compliance or legality, or any other intellectual property rights compliance, or any resulting loss or damage. Further, we are not liable for any kind of damages, losses or action arising directly or indirectly due to any content, including any errors or omissions in any content, access and/or use of the content on the Platforms or any of them including but not limited to content based decisions resulting in loss of data, revenue, profits, property, infection by viruses etc.</p>
<p>All of the data on products and promotions including but not limited to, the prices and the availability of any product or service or any feature thereof, is subject to change without notice by the party providing the product or promotion. You should use discretion while using the Platforms.</p>
<p>Weblistr reserves the right, in its sole discretion and without any obligation, to make improvements to, or correct any error or omissions in, any portion of the Platforms. Where appropriate, we will endeavor to update information listed on the Website on a timely basis, but shall not be liable for any inaccuracies.</p>
<p>All rights, title and interest including trademarks and copyrights in respect of the domain name and Platforms content hosted on the Platforms are reserved with Weblistr. Users are permitted to read, print or download text, data and/or graphics from the Website or any other Platforms for their personal use only. Unauthorized access, reproduction, redistribution, transmission and/or dealing with any information contained in the Platforms in any other manner, either in whole or in part, are strictly prohibited, failing which strict legal action will be initiated against such users.</p>
<p>Links to external Internet sites may be provided within the content on Website or other Platforms as a convenience to users. The listing of an external site does not imply endorsement of the site by Weblistr or its affiliates. Weblistr does not make any representations regarding the availability and performance of its Platforms or any of the external websites to which we provide links. When you click on advertiser banners, sponsor links, or other external links from the Website or other Platforms, your browser automatically may direct you to a new browser window that is not hosted or controlled by Weblistr.</p>
<p>Weblistr and its affiliates are not responsible for the content, functionality, authenticity or technological safety of these external sites. We reserve the right to disable links to or from third-party sites to any of our Platforms, although we are under no obligation to do so. This right to disable links includes links to or from advertisers, sponsors, and content partners that may use our Marks as part of a co-branding relationship.</p>
<p>Some external links may produce information that some people find objectionable, inappropriate, or offensive. We are not responsible for the accuracy, relevancy, copyright compliance, legality, or decency of material contained in any externally linked websites. We do not fully screen or investigate business listing websites before or after including them in directory listings that become part of the Materials on our Platforms, and we make no representation and assume no responsibility concerning the content that third parties submit to become listed in any of these directories.</p>
<p>All those sections in the Platforms that invite reader participation will contain views, opinion, suggestion, comments and other information provided by the general public, and Weblistr will at no point of time be responsible for the accuracy or correctness of such information. Weblistr reserves the absolute right to accept/reject information from readers and/or advertisements from advertisers and impose/relax Platforms access rules and regulations for any user(s).</p>
<p>Weblistr also reserves the right to impose/change the access regulations of the Platforms , whether in terms of access fee, timings, equipment, access restrictions or otherwise, which shall be posted from time to time under these terms and conditions. It is the responsibility of users to refer to these terms and conditions each time they use the Platforms.</p>
<p>While every attempt has been made to ascertain the authenticity of the content in the Platforms, Weblistr is not liable for any kind of damages, losses or action arising directly or indirectly, due to access and/or use of the content in the Platforms including but not limited to any decisions based on content in the Platforms resulting in loss of data, revenue, profits, property, infection by viruses etc.</p>
<span class="misc">Warranty Disclaimer</span>
<p>Please remember that any provider of goods or services is entitled to register with Weblistr. Weblistr does not examine whether the advertisers are good, reputable or quality sellers of goods / service providers. You must satisfy yourself about all relevant aspects prior to availing of the terms of service. Weblistr has also not negotiated or discussed any terms of engagement with any of the advertisers. The same should be done by you. Purchasing of goods or availing of services from advertisers shall be at your own risk.</p>
<p>We do not investigate, represent or endorse the accuracy, legality, legitimacy, validity or reliability of any products, services, deals, coupons or other promotions or materials, including advice, ratings, and recommendations contained on, distributed through, or linked, downloaded or accessed from the Platforms.</p>
<p>References that we make to any names, marks, products or services of third parties or hypertext links to third party sites or information do not constitute or imply our endorsement, sponsorship or recommendation of the third party, of the quality of any product or service, advice, information or other materials displayed, purchased, or obtained by you as a result of an advertisement or any other information or offer in or in connection with the Platforms.</p>
<p>Any use of the Platforms, reliance upon any Materials, and any use of the Internet generally shall be at your sole risk. Weblistr disclaims any and all responsibility or liability for the accuracy, content, completeness, legality, reliability, or operability or availability of information or material displayed in the search results in the Platforms.</p>
<div class="web_bold">
<p>The material and the platforms used to provide the material (including the website ) are provided "as is" and "as available" without warranty of any kind, either express or implied or statutory, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, or non-infringement. weblistr disclaims, to the fullest extent permitted under law, any warranties regarding the security, reliability, timeliness, accuracy and performance of the platforms and materials. Weblistr does not warrant that any defects or errors will be corrected; or that the content is free of viruses or other harmful components.</p>
<p>Weblistr disclaims any and all warranties to the fullest extent of the law, including any warranties for any information, goods, or services, obtained through, advertised or received through any links provided by or through the platforms some countries or other jurisdictions do not allow the exclusion of implied warranties, so the above exclusions may not apply to you. You may also have other rights that vary from country to country and jurisdiction to jurisdiction.</p>
<span class="misc">Disclaimer for "Weblistr Guarantee" and "Weblistr’s Right"</span>
<p>The "Weblistr Guarantee" and "Weblistr’s Right" is a limited assurance offered by Weblistr that the name and contact information of the advertiser and the category in which the advertiser is listed by Weblistr, have been verified as existing and correct at the time of the advertiser's application to register with Weblistr. Weblistr makes no representations or warranties, whether express or implied, including but not limited to warranties of the continued existence and/or operations of the advertiser, or the quality, quantity, merchantability or fitness for use of the goods or services offered by the advertiser.</p>
<span class="misc">Additional Disclaimer</span>
<p>Users using any of Weblistr service across the following mediums ie. through internet ie www.Weblistr.com Website, Wapsite, SMS, phone or any other medium are bound by this additional disclaimer wherein they are cautioned to make proper enquiry before they (Users) rely, act upon or enter into any transaction (any kind or any sort of transaction including but not limited to monetary transaction ) with the Advertiser listed with Weblistr.</p>
<p>All the Users are cautioned that all and any information of whatsoever nature provided or received from the Advertiser/s is taken in good faith, without least suspecting the bonafides of the Advertiser/s and Weblistr does not confirm, does not acknowledge, or subscribe to the claims and representation made by the Advertiser/s listed with Weblistr .Further, Weblistr is not at all responsible for any act of Advertiser/s listed at Weblistr.</p>
<span class="misc">Limitation of Liability</span>
<p>In no event shall weblistr be liable to any user on account of such user's use, misuse or reliance on the platforms for any damages whatsoever, including direct, special, punitive, indirect, consequential or incidental damages or damages for loss of profits, revenue, use, or data whether brought in warranty, contract, intellectual property infringement, tort (including negligence) or other theory, even if weblistr are aware of or have been advised of the possibility of such damage, arising out of or connected with the use (or inability to use) or performance of the platforms, the materials or the internet generally, or the use (or inability to use), reliance upon or performance of any material contained in or accessed from any platforms. Weblistr does not assume any legal liability or responsibility for the accuracy, completeness, or usefulness of any information, apparatus, product or process disclosed on the platforms or other material accessible from the platforms.</p>
<p>The user of the platforms assumes all responsibility and risk for the use of this platforms and the internet generally. The foregoing limitations shall apply notwithstanding any failure of the essential purpose of any limited remedy and to the fullest extent permitted under applicable law. Some countries do not allow the exclusion or limitation of liability of consequential or incidental damages, so the above exclusions may not apply to all users; in such countries liability is limited to the fullest extent permitted by law.</p>
<span class="misc">Third Party Sites</span>
<p>Your correspondence or business dealing with or participation in the sales promotions of advertisers or service providers found on or through the Platforms, including payment and delivery of related goods or services, and any other terms, conditions, and warranties or representations associated with such dealings, are solely between you and such advertisers or service providers. You assume all risks arising out of or resulting from your transaction of business over the Internet, and you agree that we are not responsible or liable for any loss or result of the presence of information about or links to such advertisers or service providers on the Platforms. You acknowledge and agree that we are not responsible or liable for the availability, accuracy, authenticity, copyright compliance, legality, decency or any other aspect of the content, advertising, products, services, or other materials on or available from such sites or resources. You acknowledge and agree that your use of these linked sites is subject to different terms of use than these Terms, and may be subject to different privacy practices than those set forth in the Privacy Policy governing the use of the Platforms . We do not assume any responsibility for review or enforcement of any local licensing requirements that may be applicable to businesses listed on the Platforms.</p>
<span class="misc">Monitoring of Materials Transmitted by you</span>
<p>Changes may be periodically incorporated into the Platforms.Weblistr may make improvements and/or changes in the products, services and/or programs described in these Platforms and the Materials at any time without notice. We are under no obligation to monitor the material residing on or transmitted to the Platforms . However, anyone using the Platforms agrees that Weblistr may monitor the Platforms contents periodically to (1) comply with any necessary laws, regulations or other governmental requests; (2) to operate the Platforms properly or to protect itself and its users. Weblistr reserves the right to modify, reject or eliminate any material residing on or transmitted to its Platforms that it, in its sole discretion, believes is unacceptable or in violation of the law or these Terms and Conditions. DELETIONS FROM SERVICE: Weblistr will delete any materials at the request of the user who submitted the materials or at the request of an advertiser who has decided to "opt-out" of the addition of materials to its advertising, including, but not limited to ratings and reviews provided by third parties. Weblistr reserves the right to delete (or to refuse to post to public forums) any materials it deems detrimental to the system or is, or in the opinion of Weblistr, may be, defamatory, infringing or violate of applicable law. Weblistr reserves the right to exclude Material from the Platforms. Materials submitted to Weblistr for publication on the Platforms may be edited for length, clarity and/or consistency with Weblistr's editorial standards.</p>
<span class="misc" style="text-transform:capitalize;">INDEMNIFICATION</span>
<p>You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, officers, directors, agents, and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your breach of these Terms, your violation of any law, or your violation of the rights of a third party, including the infringement by you of any intellectual property or other right of any person or entity. These obligations will survive any termination of the Terms.</p>
<span class="misc" style="text-transform:capitalize;">MISCELLANEOUS</span>
<p>These Terms will be governed by and construed in accordance with the Indian laws, without giving effect to its conflict of laws provisions or your actual state or country of residence, and you agree to submit to personal jurisdiction in India. You agree to exclude, in its entirety, the application to these Terms of the United Nations Convention on Contracts for the International Sale of Goods. You are responsible for compliance with applicable laws. If for any reason a court of competent jurisdiction finds any provision or portion of the Terms to be unenforceable, the remainder of the Terms will continue in full force and effect. These Terms constitute the entire agreement between us and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding the subject matter of these Terms. Any waiver of any provision of the Terms will be effective only if in writing and signed by you and Weblistr. Weblistr reserves the right to investigate complaints or reported violations of these Terms and to take any action we deem necessary and appropriate. Such action may include reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties. In addition, we may take action to disclose any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information. Weblistr reserves the right to seek all remedies available at law and in equity for violations of these Terms.</p>
<p><span class="misc">Notices</span> All of our notices, demands and other communications must be in writing and will be deemed to have been given (a) if mailed by certified mail, postage prepaid, (b) if delivered by overnight courier, (c) if sent by facsimile transmission and such transmission is confirmed as received, or (d) if sent by electronic mail, and such message is confirmed as received, in each case to the address, fax number or e-mail address specified on the Order for the recipient of such notice. All of your notices, demands and other communications must be in writing and will be deemed to have been given (a) if mailed by certified mail, postage prepaid or if delivered by overnight courier, to our address: WeblistrHarrington Mansion 3rd Floor 28/4, Ho Chi Minh Sarani, Kolkata 700 071.</p>
<p>Force Majeure. In no event shall we or any Distribution Site have liability or be deemed to be in breach hereof for any failure or delay of performance resulting from any governmental action, fire, flood, insurrection, earthquake, power failure, network failure, riot, explosion, embargo, strikes (whether legal or illegal), terrorist act, labor or material shortage, transportation interruption of any kind or work slowdown or any other condition not reasonably within our control. Your payment obligations shall continue during any event of force majeure. </p>
<p><span class="misc">Indemnification</span>You agree to indemnify us and the Distribution Sites and hold us and the Distribution Site harmless from and with respect to any claims, actions, liabilities, losses, expenses, damages and costs (including, without limitation, actual attorneys' fees) that may at any time be incurred by us or them arising out of or in connection with these Terms or any Advertising Products or services you request, including, without limitation, any claims, suits or proceedings for defamation or libel, violation of right of privacy or publicity, criminal investigations, infringement of intellectual property, false or deceptive advertising or sales practices and any virus, contaminating or destructive features. </p>
<p><span class="misc">Telephone Conversations</span>All telephone conversations between you and us about your advertising may be recorded and you hereby consent to such monitoring and recordation. </p>
<p><span class="misc">Arbitration:</span> Any disputes and differences whatsoever arising in connection with these Terms shall be settled by Arbitration in accordance with the Arbitration and Conciliation Act, 1996. a) All proceedings shall be conducted in English language. b) Unless the Parties agree on a sole arbitrator there shall be three Arbitrators, one to be selected by each of the parties, and the third to be selected by the two Arbitrators appointed by the parties. c) The venue of Arbitration shall be in Kolkata, India.</p>
<p><span class="misc">Entire Agreement</span>These Terms constitutes the entire agreement between you and us with respect to the subject matter of these Terms and supersedes all prior written and all prior or contemporaneous oral communications regarding such subject matter. Accordingly, you should not rely on any representations or warranties that are not expressly set forth in these Terms. If any provision or provisions of these Terms shall be held to be invalid, illegal, unenforceable or in conflict with the law of any jurisdiction, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired. Except as provided in Section 1, these Terms may not be modified except by writing signed by you and us; provided, however, we may change these Terms from time to time, and such revised terms and conditions shall be effective with respect to any Advertising Products ordered after written notice of such revised terms to you or, if earlier, posting of such revised terms and conditions on our Website.</p>
</div>
</div>
</div>
</div>
</section>